const axios = require('axios').default;

const httpCall = async (orgName) => {
    try {
        const response = await axios.request(
            {
                url: `https://p11281411c1prd-admin.occa.ocs.oraclecloud.com/ccadminui/v1/organizations?fields=totalResults,offset,limit,items.id,items.organizationLogoURL,items.name,items.parentOrganization.name,items.parentOrganization.repositoryId,items.ancestorOrganizations,items.allMembersCount&allMembersCount=true&useAdvancedQParser=true&expand=basic&limit=40&sort=name:asc&q=(name co "${orgName}")`,
                method: 'get',
                headers: {
                    'content-type': 'application/json',
                    'Authorization': `Bearer eyJhbGciOiJSUzI1NiIsImprdSI6InAxMTI4MTQxMWMxUFJEIiwia2lkIjoiMCIsIng1YyI6bnVsbCwieDV1IjoiaHR0cHM6Ly9wMTEyODE0MTFjMXByZC1hZG1pbi5vY2NhLm9jcy5vcmFjbGVjbG91ZC5jb20vY2NhZG1pbi92MS90ZW5hbnRDZXJ0Q2hhaW4ifQ==.eyJpYXQiOjE2ODI0MTMyMjgsImV4cCI6MTY4MjQxNjgyOCwic3ViIjoidmlrcmFtLm5hcmF5YW5hcHBhQGFwZXhpdC5jb20iLCJhdWQiOiJhZG1pblVJIiwiY29tLm9yYWNsZS5hdGcuY2xvdWQuY29tbWVyY2Uucm9sZXMiOlsiYWRtaW5Sb2xlIl0sIm9jY3MuYWRtaW4ucm9sZXMiOlsiYWRtaW5Sb2xlIl0sImlzcyI6Imh0dHBzOi8vcDExMjgxNDExYzFwcmQtYWRtaW4ub2NjYS5vY3Mub3JhY2xlY2xvdWQuY29tL29jY3MtYWRtaW4iLCJvY2NzLmFkbWluLmxvY2FsZSI6ImVuX1VTIiwib2Njcy5hZG1pbi50eiI6bnVsbCwib2Njcy5hZG1pbi50ZW5hbnRUeiI6IkFtZXJpY2EvQ2hpY2FnbyIsIm9jY3MuYWRtaW4ua2VlcEFsaXZlVVJMIjoiaHR0cHM6Ly9wMTEyODE0MTFjMXByZC1hZG1pbi5vY2NhLm9jcy5vcmFjbGVjbG91ZC5jb20va2VlcGFsaXZlIiwib2Njcy5hZG1pbi50b2tlblJlZnJlc2hVUkwiOiJodHRwczovL3AxMTI4MTQxMWMxcHJkLWFkbWluLm9jY2Eub2NzLm9yYWNsZWNsb3VkLmNvbS9jY2FkbWluL3YxL3Nzb1Rva2Vucy9yZWZyZXNoIiwib2Njcy5hZG1pbi52ZXJzaW9uIjoiMjMuMS4xIiwib2Njcy5hZG1pbi5idWlsZCI6ImplbmtpbnMtQXNzZW1ibGVfQ2xvdWRfQ29tbWVyY2VfRUFSc18tbWFzdGVyLTI3MSIsIm9jY3MuYWRtaW4uZW1haWwiOiJ2aWtyYW0ubmFyYXlhbmFwcGFAYXBleGl0LmNvbSIsIm9jY3MuYWRtaW4ucHJvZmlsZUlkIjoiaXVzZXI0ODg2ODM4Iiwib2Njcy5hZ2VudC5vYm8iOm51bGwsIm9jY3MuYWRtaW4uZmlyc3ROYW1lIjoiVmlrcmFtIiwib2Njcy5hZG1pbi5sYXN0TmFtZSI6Ik5hcmF5YW5hcHBhIiwib2Njcy5hZG1pbi5wdW5jaG91dFVzZXIiOmZhbHNlLCJzdWJfdHlwZSI6bnVsbCwic2NvcGUiOm51bGx9.F2C0En1yg4zTCiPXLxS456d8cBDYXzgppRhtZUSBszbZh4Y49iyv33O/kGNJB3/OCDyW8YgGt/1Y9iqmst3TeB0TM/lpBCW1K3GnzzqzXzeUxO4V2xCkYtCgWYcHc+vJ7x4V2u4kbZAVfWlQwmzLpfGK4XjXDflEszlsAm2GGy532aKvSZYwej4XtR+BZSSvRUrCjYljTqIXm86C/RIPWQ4UlU6CusUjjMeBMtzZb2nc5qQ27mhcbFUw6eTvDsPtiH+8cdwArR/TDvp7kZlwxd2RUL8izcO4SuvIqkoTLNaZ9SArOPMWpvy0WaI6mkCcENDPYt3jaBLaisQOodxm5w==`
                }
            }
        );
        if (!response.data?.items[0]?.name) {
            console.log(orgName)
        }
    } catch (err) {

    }

}

const list = `KIMBLE RECYCLING & DISPOSAL INC
RUSH TRUCK CENTER - 575
GOVERNMENT OF THE CAYMAN ISLANDS
INTERSTATE WASTE SERVICES
INTERSTATE WASTE SERVICES
INTERSTATE WASTE SERVICES
INTERSTATE WASTE SERVICES
INTERSTATE WASTE SERVICES 543
INTERSTATE WASTE SERVICES INC
INTERSTATE WASTE SERVICES INC 543
INTERSTATE WASTE SERVICES INC 543
INTERSTATE WASTE SERVICES INC 543
INTERSTATE WASTE SERVICES INC 543
INTERSTATE WASTE SERVICES INC 543
INTERSTATE WASTE SERVICES INC 543
INTERSTATE WASTE SERVICES INC 543
INTERSTATE WASTE SERVICES INC 543
TRUCK COUNTRY OF WI 530
TRUCK COUNTRY OF WI 530
TRUCK COUNTRY OF WI 530
FLEETPRIDE
BUILDERS CONCRETE EAST LLC 492
BUILDERS CONCRETE EAST LLC 492
KIMBLE RECYCLING & DISPOSAL INC
SMYRNA READY MIX 290
SMYRNA READY MIX 290
SMYRNA READY MIX LLC 290
SMYRNA READY MIX LLC 290
SMYRNA READY MIX 290
GCI RESIDENTIAL - 155
GCI RESIDENTIAL - 155
FCC ENVIRONMENTAL SERVICES - 085
FCC ENVIRONMENTAL SERVICES - 085
CAMIONES Y MOTORES SA IT5
CAMIONES Y MOTORES SA IT5
CAMIONES Y MOTORES SA IT5
CAMIONES Y MOTORES SA IT5
CARGOTECNIA CENTROAMERICANA SA IT3
CONSORCIO MANTENEQUIPOS INC
EAGLE TRADE S A
INDUSTRIAS IVOR SA IT3
INDUSTRIAS IVOR SA IT3
INDUSTRIAS IVOR SA IT3
INDUSTRIAS IVOR SA IT3
INDUSTRIAS IVOR SA IT3
INDUSTRIAS IVOR SA IT3
INDUSTRIAS IVOR SA IT3
INDUSTRIAS IVOR SA IT3
INTERSTATE WASTE SERVICES 543
MASSY MACHINERY LTD
MEZCLADORAS Y TRAILERS DE MEXICO
MEZCLADORAS Y TRAILERS DE MEXICO
MEZCLADORAS Y TRAILERS DE MEXICO
MEZCLADORAS Y TRAILERS DE MEXICO
PRIVATE JOINT STOCK COMPANY IT3
TECNICA UNIVERSAL S.A.
AGENCIA ALEMANA DE NICARAGUA SA
AGENCIA DE VEHICULOS KENWORTH DE C.A.,SA
AGENCIA DE VEHICULOS KENWORTH DE C.A.,SA
AGREGADOS Y CONCRETOS SA
AGREGADOS Y CONCRETOS SA
BESSA RD/TT & BEST EQUIPMENT SERVICE SA
BESSA RD/TT & BEST EQUIPMENT SERVICE SA
CARGOTECNIA EQUIPOS SA DE CV IT3
CARGOTECNIA EQUIPOS SA DE CV IT3
CARGOTECNIA EQUIPOS SA DE CV IT3
CARGOTECNIA EQUIPOS SA DE CV IT3
CARIBBEAN MACHINERY PARTS & SERVICES LLC
CONSORCIO MANTENEQUIPOS INC`;

// [...new Set(list.split(`
// `))].forEach(async (org) => {
//     await httpCall(org);
// })

console.log([...new Set(list.split(`
`))].length)